# Generated by Django 5.2 on 2025-04-10 19:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloom', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('manager', 'Manager'), ('designer', 'Designer'), ('arranger', 'Flower Arranger'), ('delivery', 'Delivery Personnel'), ('sales', 'Sales Associate'), ('customer_service', 'Customer Service')], max_length=20)),
                ('department', models.CharField(blank=True, max_length=50)),
                ('hire_date', models.DateField(default=django.utils.timezone.now)),
                ('phone_extension', models.CharField(blank=True, max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('can_process_orders', models.BooleanField(default=False)),
                ('can_arrange_flowers', models.BooleanField(default=False)),
                ('can_deliver_orders', models.BooleanField(default=False)),
                ('can_manage_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='assigned_delivery',
            field=models.ForeignKey(blank=True, limit_choices_to={'can_deliver_orders': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_orders', to='bloom.employee'),
        ),
        migrations.AddField(
            model_name='order',
            name='assigned_designer',
            field=models.ForeignKey(blank=True, limit_choices_to={'can_arrange_flowers': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='design_orders', to='bloom.employee'),
        ),
        migrations.AddField(
            model_name='order',
            name='processed_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'can_process_orders': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_orders', to='bloom.employee'),
        ),
        migrations.AddField(
            model_name='orderstatus',
            name='updated_by_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bloom.employee'),
        ),
        migrations.CreateModel(
            name='EmployeeOrderAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('manager', 'Manager'), ('designer', 'Designer'), ('arranger', 'Flower Arranger'), ('delivery', 'Delivery Personnel'), ('sales', 'Sales Associate'), ('customer_service', 'Customer Service')], max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='made_assignments', to='bloom.employee')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloom.employee')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloom.order')),
            ],
            options={
                'ordering': ['-assigned_at'],
                'unique_together': {('employee', 'order', 'completed')},
            },
        ),
    ]
