# Generated by Django 5.2 on 2025-04-10 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloom', '0002_employee_order_assigned_delivery_and_more'),
        ('shop', '0002_coupon_order_discount_amount_order_coupon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shop_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bloom_order_link', to='shop.order'),
        ),
    ]
