# Generated by Django 5.2 on 2025-04-10 06:34

from django.db import migrations


def migrate_customers_to_contact_persons(apps, schema_editor):
    """
    Create ContactPerson records for each existing Customer,
    making them the primary contact and preserving their name, email and phone.
    """
    Customer = apps.get_model("bloom", "Customer")
    ContactPerson = apps.get_model("bloom", "ContactPerson")

    for customer in Customer.objects.all():
        # Try to split the name into first and last name
        name_parts = customer.name.strip().split(maxsplit=1)
        if len(name_parts) > 1:
            first_name, last_name = name_parts
        else:
            first_name = name_parts[0] if name_parts else "Unknown"
            last_name = ""

        # Create a contact person for this customer
        ContactPerson.objects.create(
            customer=customer,
            first_name=first_name,
            last_name=last_name,
            email=customer.email,
            phone=customer.phone,
            is_primary_contact=True,
        )


def reverse_migrate_customers(apps, schema_editor):
    """
    Remove all ContactPerson records (no need to modify Customer records
    since their fields are preserved)
    """
    ContactPerson = apps.get_model("bloom", "ContactPerson")
    ContactPerson.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("bloom", "0002_customer_company_name_customer_contact_type_and_more"),
    ]

    operations = [
        migrations.RunPython(
            migrate_customers_to_contact_persons, reverse_migrate_customers
        ),
    ]
