# Generated by Django 5.2 on 2025-04-10 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloom', '0003_order_shop_order'),
        ('shop', '0003_order_bloom_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shop_product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bloom_product_link', to='shop.product'),
        ),
    ]
