# Generated by Django 5.2 on 2025-04-11 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloom', '0003_migrate_customers_to_contact_persons'),
        ('bloom', '0004_product_shop_product'),
    ]

    operations = [
    ]
