# Generated by Django 5.2 on 2025-04-21 04:33

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone


def create_order_works(apps, schema_editor):
    """
    Create OrderWork instances for each existing Order, transferring delivery info
    and updating related OrderItem instances.
    """
    Order = apps.get_model("bloom", "Order")
    OrderWork = apps.get_model("bloom", "OrderWork")
    OrderItem = apps.get_model("bloom", "OrderItem")

    # For each order, create a corresponding OrderWork
    for order in Order.objects.all():
        # Create the OrderWork with the delivery details from the Order
        orderwork = OrderWork.objects.create(
            order=order,
            shipment_date=getattr(order, "shipment_date", None),
            delivery_method=getattr(order, "delivery_method", None),
            shipping_charge=getattr(order, "shipping_charge", 0),
            recipient_name=getattr(order, "recipient_name", ""),
            recipient_phone=getattr(order, "recipient_phone", ""),
            shipping_address=getattr(order, "shipping_address", None),
            shipping_city=getattr(order, "shipping_city", None),
            shipping_state=getattr(order, "shipping_state", None),
            shipping_country=getattr(order, "shipping_country", None),
            shipping_postal_code=getattr(order, "shipping_postal_code", None),
            assigned_designer=getattr(order, "assigned_designer", None),
            assigned_delivery=getattr(order, "assigned_delivery", None),
            status=order.status,
            notes="Automatically created from order migration",
            subtotal=order.subtotal,
            created_at=order.created_at,
            updated_at=order.updated_at,
        )

        # Update all OrderItems to link to this OrderWork instead of the Order
        for item in OrderItem.objects.filter(order=order):
            item.orderwork = orderwork
            item.order = None
            item.save()

        # Update the order's total based on the orderwork
        # Recalculate the order total directly instead of calling a model method
        total = 0
        for work in OrderWork.objects.filter(order=order):
            total += work.subtotal

        order.subtotal = total

        # Apply discounts and taxes
        if order.discount_value > 0:
            if order.is_discount_before_tax:
                subtotal_after_discount = total - order.discount_value
                order.total = subtotal_after_discount + order.tax_amount
            else:
                order.total = total + order.tax_amount - order.discount_value
        elif order.discount_percentage > 0:
            discount = total * (order.discount_percentage / 100)
            if order.is_discount_before_tax:
                subtotal_after_discount = total - discount
                order.total = subtotal_after_discount + order.tax_amount
            else:
                order.total = total + order.tax_amount - discount
        else:
            order.total = total + order.tax_amount

        order.save()


def reverse_create_order_works(apps, schema_editor):
    """
    Reverse the migration by moving data from OrderWork back to Order
    """
    Order = apps.get_model("bloom", "Order")
    OrderWork = apps.get_model("bloom", "OrderWork")
    OrderItem = apps.get_model("bloom", "OrderItem")

    # For each OrderWork, move data back to the parent Order
    for orderwork in OrderWork.objects.all():
        order = orderwork.order

        # Move delivery details back to Order
        order.shipment_date = orderwork.shipment_date
        order.delivery_method = orderwork.delivery_method
        order.shipping_charge = orderwork.shipping_charge
        order.recipient_name = orderwork.recipient_name
        order.recipient_phone = orderwork.recipient_phone
        order.shipping_address = orderwork.shipping_address
        order.shipping_city = orderwork.shipping_city
        order.shipping_state = orderwork.shipping_state
        order.shipping_country = orderwork.shipping_country
        order.shipping_postal_code = orderwork.shipping_postal_code
        order.assigned_designer = orderwork.assigned_designer
        order.assigned_delivery = orderwork.assigned_delivery

        # Update the order's subtotal from the orderwork
        order.subtotal = orderwork.subtotal

        # Move items back to Order
        for item in OrderItem.objects.filter(orderwork=orderwork):
            item.order = order
            item.orderwork = None
            item.save()

        # Recalculate total with the same logic as before
        total = order.subtotal

        # Apply discounts and taxes
        if order.discount_value > 0:
            if order.is_discount_before_tax:
                subtotal_after_discount = total - order.discount_value
                order.total = subtotal_after_discount + order.tax_amount
            else:
                order.total = total + order.tax_amount - order.discount_value
        elif order.discount_percentage > 0:
            discount = total * (order.discount_percentage / 100)
            if order.is_discount_before_tax:
                subtotal_after_discount = total - discount
                order.total = subtotal_after_discount + order.tax_amount
            else:
                order.total = total + order.tax_amount - discount
        else:
            order.total = total + order.tax_amount

        order.save()


class Migration(migrations.Migration):

    dependencies = [
        ("bloom", "0005_merge_20250411_0610"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderWorkStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("processing", "Processing"),
                            ("preparation", "Preparation"),
                            ("delivery", "Delivery"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name_plural": "Order Work Statuses",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeOrderWorkAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("manager", "Manager"),
                            ("designer", "Designer"),
                            ("arranger", "Flower Arranger"),
                            ("delivery", "Delivery Personnel"),
                            ("sales", "Sales Associate"),
                            ("customer_service", "Customer Service"),
                        ],
                        max_length=20,
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="made_orderwork_assignments",
                        to="bloom.employee",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bloom.employee"
                    ),
                ),
            ],
            options={
                "ordering": ["-assigned_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderWork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shipment_date", models.DateField(null=True)),
                (
                    "shipping_charge",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("recipient_name", models.CharField(blank=True, max_length=100)),
                ("recipient_phone", models.CharField(blank=True, max_length=20)),
                ("shipping_address", models.TextField(blank=True, null=True)),
                (
                    "shipping_city",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "shipping_state",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "shipping_country",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "shipping_postal_code",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("processing", "Processing"),
                            ("preparation", "Preparation"),
                            ("delivery", "Delivery"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_delivery",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"can_deliver_orders": True},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="delivery_orderworks",
                        to="bloom.employee",
                    ),
                ),
                (
                    "assigned_designer",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"can_arrange_flowers": True},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="design_orderworks",
                        to="bloom.employee",
                    ),
                ),
                (
                    "delivery_method",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bloom.deliverymethod",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orderworks",
                        to="bloom.order",
                    ),
                ),
            ],
        ),
        migrations.RunPython(create_order_works, reverse_create_order_works),
        migrations.RemoveField(
            model_name="order",
            name="assigned_delivery",
        ),
        migrations.RemoveField(
            model_name="order",
            name="assigned_designer",
        ),
        migrations.RemoveField(
            model_name="order",
            name="delivery_method",
        ),
        migrations.RemoveField(
            model_name="order",
            name="recipient_name",
        ),
        migrations.RemoveField(
            model_name="order",
            name="recipient_phone",
        ),
        migrations.RemoveField(
            model_name="order",
            name="shipment_date",
        ),
        migrations.RemoveField(
            model_name="order",
            name="shipping_address",
        ),
        migrations.RemoveField(
            model_name="order",
            name="shipping_charge",
        ),
        migrations.RemoveField(
            model_name="order",
            name="shipping_city",
        ),
        migrations.RemoveField(
            model_name="order",
            name="shipping_country",
        ),
        migrations.RemoveField(
            model_name="order",
            name="shipping_postal_code",
        ),
        migrations.RemoveField(
            model_name="order",
            name="shipping_state",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="order",
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("processing", "Processing"),
                    ("preparation", "Preparation"),
                    ("delivery", "Delivery"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="new",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="orderstatus",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("processing", "Processing"),
                    ("preparation", "Preparation"),
                    ("delivery", "Delivery"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="orderworkstatus",
            name="orderwork",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="bloom.orderwork"
            ),
        ),
        migrations.AddField(
            model_name="orderworkstatus",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.customuser",
            ),
        ),
        migrations.AddField(
            model_name="orderworkstatus",
            name="updated_by_employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="bloom.employee",
            ),
        ),
        migrations.AddField(
            model_name="employeeorderworkassignment",
            name="orderwork",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="bloom.orderwork"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="employeeorderworkassignment",
            unique_together={("employee", "orderwork", "completed")},
        ),
    ]
