# Generated by Django 5.2 on 2025-04-21 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloom', '0006_orderworkstatus_remove_order_assigned_delivery_and_more'),
        ('shop', '0005_remove_order_address_line_1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orderwork',
            name='shop_orderwork',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bloom_orderwork_link', to='shop.orderwork'),
        ),
        migrations.AddField(
            model_name='employeeorderworkassignment',
            name='orderwork',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloom.orderwork'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='orderwork',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderitems', to='bloom.orderwork'),
        ),
        migrations.AddField(
            model_name='orderworkstatus',
            name='orderwork',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloom.orderwork'),
        ),
        migrations.AddField(
            model_name='orderworkstatus',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderworkstatus',
            name='updated_by_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bloom.employee'),
        ),
        migrations.AlterUniqueTogether(
            name='employeeorderworkassignment',
            unique_together={('employee', 'orderwork', 'completed')},
        ),
    ]
