# Generated by Django 5.2 on 2025-04-10 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloom', '0004_product_shop_product'),
        ('shop', '0003_order_bloom_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='product_type',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_category', to='bloom.producttype'),
        ),
    ]
